### ISSUE TITLE
前端项目运行出现 No ESLint configuration found 提示

### ISSUE THREAD

**Issue by alex-oos** [duxiaoman/AnyMock#11]
想请问问，前端项目运行出现 No ESLint configuration found 这样的提示应该如何解决呢？

**Comment by alex-oos** [comment]
大神可否帮忙看看呢？

**Comment by ReneJiang** [comment]
> 想请问问，前端项目运行出现 No ESLint configuration found 这样的提示应该如何解决呢？

没有遇到过，提供一下部署方式和更多信息

**Comment by kevynull** [comment]
> > 想请问问，前端项目运行出现 No ESLint configuration found 这样的提示应该如何解决呢？
> 
> 没有遇到过，提供一下部署方式和更多信息

这边也碰到了，源码不全，少了eslint的config文件（.eslintrc.js）。目前最简单的解决方案是直接关闭eslint。否则后续会配置、风格、属性没有使用等一系列错误。

**Comment by zhaohuijin** [comment]
我关闭掉了eslint，但是接下来提示Syntax Error: SyntaxError: D:/IDEA Project/AnyMock-master/anymock-fe/src/lang/index.js: Unexpected token (15:4)

  13 | const messages = {
  14 |   en: {
> 15 |     ...enLocale,
     |     ^
  16 |     ...elementEnLocale
  17 |   },
  18 |   zh: {
请问大佬遇到过这个问题吗？总感觉前端的源码不全，不知道作者啥时候有空会更新一下

**Comment by alex-oos** [comment]
> > 想请问问，前端项目运行出现 No ESLint configuration found 这样的提示应该如何解决呢？
> 
> 没有遇到过，提供一下部署方式和更多信息

好的，谢谢了

**Comment by alex-oos** [comment]
> > > 想请问问，前端项目运行出现 No ESLint configuration found 这样的提示应该如何解决呢？
> > 
> > 没有遇到过，提供一下部署方式和更多信息
> 
> 这边也碰到了，源码不全，少了eslint的config文件（.eslintrc.js）。目前最简单的解决方案是直接关闭eslint。否则后续会配置、风格、属性没有使用等一系列错误。

好嘞，谢谢啦
